export enum AnalyticsEvent {
  google_play_pressed = "google_play_pressed",
  header_pressed = "header_pressed",
  terms_of_service_pressed = "terms_of_service_pressed",
  privacy_policy_pressed = "privacy_policy_pressed",
  photo_gallery_pressed = "photo_gallery_pressed",
  join_mailing_list = "join_mailing_list",
  email_write_pressed = "email_write_pressed",
  first_card_pressed = "first_card_pressed",
  second_card_pressed = "second_card_pressed",
  third_card_pressed = "third_card_pressed",
  go_to_home_page_pressed = "go_to_home_page_pressed",
  apple_store_pressed = "apple_store_pressed",
  go_to_home_page_available_soon = "go_to_home_page_available_soon",
  google_play_available_soon_pressed = "google_play_available_soon_pressed",
  error_TarotCardFullDescription = "error_TarotCardFullDescription",
  error_RoutesSuitMinorArcana = "error_RoutesSuitMinorArcana",
  error_RoutesPage = "error_RoutesPage",
}
